#!/bin/sh

if [ "X$1" = "Xstart" ]; then
  echo "S10setup: remount / rw"
  mount -o remount,rw /
  
  echo "S10setup: checking keys"
  # Make sure dropbear directory exists
  if [ ! -d /etc/dropbear ] ; then
    mkdir -p /etc/dropbear
  fi
  
  # Check for the Dropbear RSA key
  if [ ! -f /etc/dropbear/dropbear_rsa_host_key ] ; then
    echo -n "generating rsa key... "
    /usr/bin/dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key > /dev/null 2>&1
  fi
  
  # Check for the Dropbear DSS key
  if [ ! -f /etc/dropbear/dropbear_dss_host_key ] ; then
    echo -n "generating dsa key... "
    /usr/bin/dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key > /dev/null 2>&1
  fi
  
  echo "S10setup: moving /media"
  # /media is where usb drives mount, move it to /tmp and bind
  mkdir -p /tmp/media
  cp -a /media /tmp/
  mount -o bind /tmp/media /media
  
  echo "S10setup: mounting /tmp/userdata"
  # find userdata via mtd partition name, mount it and bind to /root
  for i in `ls /dev/mtd* | grep -o "mtd[0-9]$"`; do
    if [[ "`cat /sys/devices/virtual/mtd/$i/name`" == "userdata" ]]; then
      USERDATA="/dev/"`ls /sys/devices/virtual/mtd/$i | grep -o mtdblock[0-9]`
      break
    fi
  done

  mkdir -p /tmp/userdata
  mount -t yaffs2 $USERDATA /tmp/userdata
  mkdir -p /tmp/userdata/tlbb/root
  mount -o bind /tmp/userdata/tlbb/root /root
  
  # Make .sysconfig dir on userdata partition if one does not exist
  if [ ! -d /root/.sysconfig/NetworkManager/system-connections ] ; then
     mkdir -p /root/.sysconfig/NetworkManager/system-connections
     mkdir -p /root/.sysconfig/NetworkManager/dispatcher.d
     cp -a /etc/NetworkManager/dispatcher.d/ntpd-script /root/.sysconfig/NetworkManager/dispatcher.d
  fi

  # we startup as performance, then switch to ondemand (kernel bug) and
  # if m1 or m3, limit to 600Mhz to keep audio hw from stalling.
  echo "S10setup: switching to ondemand"
  echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
  echo "600000"   > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
  #
  echo "S10setup: done"
fi
